### ISSUE TITLE
Merge Integration Strategy

### ISSUE THREAD

**Issue by bogdandit** [bogdandit/CS471WorkflowsHomeworkAssignment#2]
References user story #1

## TODO:
- [x] Click the checkboxes, which can be used as a TODO checklist for the task
- [x] Create a new PR having the **base** branch `master` and the **compare** branch `task-2_merge`
- [x] Edit the description of the PR to reference this task
- [x] Understand the commits and changes made to the PR
- [ ] In the PR, use the `Merge pull request` option to integrate the changes into `master` and the commit message should be the default one provided by GitHub (e.g., `Merge pull request #<ID_PR> from <yourGitHubUserName>/task-2_merge`)
- [ ] Use the GitHub interface to delete the branch of the PR after successfully integrating it into `master`
